### ISSUE TITLE
攻撃力高い順欲しくない？

### ISSUE THREAD

**Issue by Takonosuke-Okuyama** [Sota-Watanabe/yugioh-season-rule-assist-tool#21]
使ってて思うんだけど

**Comment by Takonosuke-Okuyama** [comment]
Fgimaにデザインあげた

期数順：今の並び方(cid昇順)
攻撃力高い順：攻撃力降順(同値はcid昇順)
守備力高い順：守備力力降順(同値はcid昇順)

**Comment by Takonosuke-Okuyama** [comment]
挙動について
個人的には　並び替えを選ぶ→検索ボタン押す→並び替え完了　でもいいと思うんだけど
世間的には　並び替えを選ぶ→並び替え完了　だよね

実装可能背であれば世間に合わせる形でお願いしたい

**Comment by Sota-Watanabe** [comment]
ユーがそのカードを出すことは既に読んでいました
世間に合わせる形、実装可能デース👍

**Comment by Sota-Watanabe** [comment]
りりーす済み

**Comment by Takonosuke-Okuyama** [comment]
テキストサイズは置いといて
![LGTM](https://images.lgtmgen.org/b4ee8430-72ed-4594-8b02-942ca2a2eeec)
