### ISSUE TITLE
database.jsonの更新

### ISSUE THREAD

**Issue by Takonosuke-Okuyama** [Sota-Watanabe/yugioh-season-rule-assist-tool#25]
魔法罠のステータスを変更(-1 → -2,-3)
notionにアップ済み

**Comment by Takonosuke-Okuyama** [comment]
ジャベリンビートル
風林火山
の画像URLが切れていたので更新(プログラムでチェックしたので、画像が表示されないことなくなるはず)

**Comment by Sota-Watanabe** [comment]
魔法罠のステータスを変更をした理由は？
https://github.com/Sota-Watanabe/yugioh-season-rule-assist-tool/issues/23
これに関係してる？

**Comment by Takonosuke-Okuyama** [comment]
並び替えることを考えるとモンスターのステータスと混ざってるのキモいかなって
